### ISSUE TITLE
pip > 10 & pip.get_installed_distributions()

### ISSUE THREAD

**Issue by nomadigital** [djaodjin/djaodjin-deployutils#9]
From https://github.com/pypa/pip/issues/5243

> See https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program - importing functions from pip is not supported. In this case, setuptools (specifically pkg_resources) probably has the functionality you need.
> 
> That's explicitly not the right thing to do. Please don't do this, we will not support such usage.

This is really an issue as we must stick with old pip version < 10 to still be able to use djaodjin-deployutils.

As far as we can see, this is only user for logging purpose in file https://github.com/djaodjin/djaodjin-deployutils/blob/master/deployutils/apps/django/logging.py

Maybe the proposed alternative in the link above can work :

```
import pkg_resources

dists = [d for d in pkg_resources.working_set]
# Filter out distributions you don't care about and use.
```

**Comment by smirolo** [comment]
commit 18f487c3 and commit 2b0f8f3d should take care of this issue - at least for pip <= 21.3.1.
